id: I8A75C641
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T05:20:52+00:00'
last_modified: '2022-06-07T13:48:53.379209+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ8068
  title: བྱང་ཆུབ་བདེ་ལམ་གྱི་ཟིན་བྲིས་ཡང་གསལ་སྒྲོན་མེ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7040':
      image_group_id: I1PD96644
      title: ''
      total_pages: 46
      order: 1
      base_file: 7040.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
